### ISSUE TITLE
distillery release :numbers dependency

### ISSUE THREAD

**Issue by matteosister** [Qqwy/elixir-rational#2]
Hi! Thanks for your work on this library, it works really well for us (building a price engine for an insurance).

distillery (we use it to deploy the artifact) is claiming that the **:numbers** dependency will not be included in the release, because it's not listed in the :applications or :included_applications configuration.

Here is the full message
```
==> One or more direct or transitive dependencies are missing from
    :applications or :included_applications, they will not be included
    in the release:

    :numbers

```

Is this a problem with ratio? Should we include it in our _applications_ list or should ratio do it?

We are using the latest version (1.2.7)

Many thanks!

**Comment by Qqwy** [comment]
Thank you very much!

Indeed, you are right. `:ratio` should add `:numbers` to its `:applications` list.

I have released a new version,  `1.2.8`, which includes this fix.

Does this new release solve the warning?

**Comment by Qqwy** [comment]
Closing because of lack of response; I'll assume this issue was solved. Feel free to open a new issue if this was not the case, of course :-).

**Comment by matteosister** [comment]
sorry for the lack of response...we totally forgot it, and yes, it's working perfectly, thanks again!
