### ISSUE TITLE
@behaviour Numeric does not exists

### ISSUE THREAD

**Issue by kipcole9** [Qqwy/elixir-rational#30]
### Environment

Elixir 1.10.0
Erlang 22.2
numbers 5.1.1
ratio 2.3.0

### Current behaviour

Compiling produces:
```
==> ratio
...
==> numbers
Compiling 7 files (.ex)
Generated numbers app
...
Compiling 2 files (.ex)
warning: @behaviour Numeric does not exist (in module Ratio)
  lib/ratio.ex:3: Ratio (module)

10
Generated ratio app
```

### Expected behaviour

Behaviour is reconciled.

**Comment by Qqwy** [comment]
Oh snap! This is an indication that I recently messed up support for `Numbers`, which changed from a behaviour-based implementation in version `4.x` to a protocol-based implementation in version `5.x`.

This is obviously an important issue that I'll dedicate some time to ASAP.
The path forward:

- Remove `@behavour` annotation.
- Implement the various `Numbers.Protocols.*` protocols.
- Write some tests to ensure future compatibility and to ensure that a situation like this does not happen again.

**Comment by kipcole9** [comment]
Thats what I guess since I saw a lot of calls to `Kernel.*` :-)
