### ISSUE TITLE
[Proposal] Support for Decimals?

### ISSUE THREAD

**Issue by kipcole9** [Qqwy/elixir-rational#31]
I'm using `ratio` in one of my libs that does [unit conversions](https://github.com/elixir-cldr/cldr_units) since [CLDR](https://cldr.unicode.org) is working on some standard unit conversion data and they are sensibly using rationals in the data definition to reduce precision errors - most conversions are two steps via a base unit.

I support both number (integer, float) values for units and also `Decimal` unit values.  I'd be curious if you're interested in adding `Decimal` support for `ratio`?  I think `numbers` already does? If so I can take a look at creating a PR.

Currently I think the constraint is on the arithmetic functions:
```
iex(1)> Ratio.new Decimal.new(0)
** (FunctionClauseError) no function clause matching in Ratio.div/2    
    
    The following arguments were given to Ratio.div/2:
     
        # 1
        #Decimal<0>
    
        # 2
        1
    
    Attempted function clauses (showing 5 out of 5):
    
        def div(a, b) when is_number(a) and is_integer(b)
        def div(a, b) when is_number(a) and is_float(b)
        def div(%Ratio{numerator: numerator, denominator: denominator}, number) when is_number(number)
        def div(number, %Ratio{numerator: numerator, denominator: denominator}) when is_number(number)
        def div(%Ratio{numerator: numerator1, denominator: denominator1}, %Ratio{numerator: numerator2, denominator: denominator2})
    
    (ratio 2.3.0) lib/ratio.ex:414: Ratio.div/2
```

**Comment by kipcole9** [comment]
I presumptively went ahead and [created a PR](https://github.com/Qqwy/elixir-rational/pull/33) to add support for `Decimal`s.

**Comment by Qqwy** [comment]
I would be very interested in adding this!

Indeed, `numbers` already supports `Decimal` as an optional dependency.

**Comment by kipcole9** [comment]
Thanks @Qqwy. I'll close this issue and we can continue discussion in the PR.
