### ISSUE TITLE
Spurious compile-time IO.puts/1

### ISSUE THREAD

**Issue by kipcole9** [Qqwy/elixir-rational#32]
In module `Ratio.FloatConversion` there is a spurious `IO.puts/1` output at compile time.
```
defmodule Ratio.FloatConversion do
  use Ratio

  @max_decimals Application.get_env(:ratio, :max_float_to_rational_digits)
  IO.puts(Application.get_env(:ratio, :max_float_to_rational_digits))

```

**Comment by kipcole9** [comment]
I presumptively went ahead and [created a PR](https://github.com/Qqwy/elixir-rational/pull/33) to add support for `Decimal`s and remove this `IO.puts/1`

**Comment by Qqwy** [comment]
Thank you! That indeed is not supposed to be there. :sweat_smile:

**Comment by Qqwy** [comment]
_(Note that I went ahead and removed the spurious statement in a separate commit to allow your PR to concentrate solely on the `Decimal` support.)_
