### ISSUE TITLE
decimal is listed incorrectly as "optional"

### ISSUE THREAD

**Issue by jdjohnston** [Qqwy/elixir-rational#9]
At hex.pm, `decimal` is listed as an optional dependency. However, when compiling an Elixir project using `ratio` but without `decimal`, `mix` complains

> == Compilation error in file lib/ratio/numbers_implementations.ex ==
** (CompileError) lib/ratio/numbers_implementations.ex:57: Decimal.__struct__/0 is undefined, cannot expand struct Decimal

Umm, this _is_ the repo for `ratio` 2.2, right? I can't find `numbers_implementations.ex`.

**Comment by Qqwy** [comment]
Very odd; it seems like the version pushed to `Hex` was older than the one in this repository.

I have published a fixed version `2.2.1`. Does this resolve the problem? :slightly_smiling_face:

**Comment by jdjohnston** [comment]
Resolved. :)
